name: MechTech
main: com.dragonflame.main.Main
version: 1.0.0
commands:
  tpa:
    usage: /<command> <player>
    description: Sends a tp request to a player
    permission: dragonflame.tpa
  tpaccept:
    usage: /<command>
    description: Accepts a tp request
    permission: dragonflame.tpa
  tpdeny:
    usage: /<command>
    description: Denies a tp request
    permission: dragonflame.tpa
  back:
    usage: /<command>
    description: Goes back to your previous location
    permission: dragonflame.back
  home:
    usage: /<command> [name]
    description: Goes to a home (max 3)
    permission: dragonflame.home
  delhome:
    usage: /<command> [name]
    description: Deletes a specified home
    permission: dragonflame.home
  sethome:
    usage: /<command> [name]
    description: Sets a specified home
    permission: dragonflame.home
  f:
    usage: /<command>
    description: Ask an operator
    permission: dragonflame.f
  spawn:
    usage: /<command>
    description: Goes to spawn
    permission: dragonflame.spawn
  temp:
    usage: /<command>
    description: Don't use this unless you wanna break everyone's homes
    permission: dragonflame.temp
  book:
    usage: /<command>
    description: Gives a detailed book containing information
    permission: dragonflame.book
  recipebook:
    usage: /<command>
    description: Gives a book containing all recipes of custom items
    permission: dragonflame.book
  oldhome:
    usage: /<command>
    description: temporary command, move these homes over to the old one.
    permission: dragonflame.old
permissions:
 dragonflame.old:
  default: true
 dragonflame.book:
  default: true
 dragonflame.spawn:
  default: true
 dragonflame.tpa:
  default: true
 dragonflame.back:
  default: true
 dragonflame.home:
  default: true
 dragonflame.f:
  default: op
 dragonflame.home.op:
  default: op
 dragonflame.temp:
  default: op